### ISSUE TITLE
Language Server is crashing in VSCode 1.54

### ISSUE THREAD

**Issue by Daylien** [erlang-ls/vscode#71]
Hey,

in the latest release of VSCode 1.54 the language server keeps constantly crashing. I have noticed this also in the Insider version earlier and thought it was a problem with the "unstable" insider channel. Now the extension is not usable anymore. I can't verify it on Windows, only on Linux (Fedora 33) and MacOS.

System info: 

```
OS: MacOS 11.2.1
Arch: arm64
Erlang version: Erlang/OTP 23.2.5
```

Crashing log:

```js
[Error - 1:43:50 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/Users/malte/.vscode/extensions/erlang-ls.erlang-ls-0.0.19/client/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/Users/malte/.vscode/extensions/erlang-ls.erlang-ls-0.0.19/client/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/Users/malte/.vscode/extensions/erlang-ls.erlang-ls-0.0.19/client/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/Users/malte/.vscode/extensions/erlang-ls.erlang-ls-0.0.19/client/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/Users/malte/.vscode/extensions/erlang-ls.erlang-ls-0.0.19/client/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/Users/malte/.vscode/extensions/erlang-ls.erlang-ls-0.0.19/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/malte/.vscode/extensions/erlang-ls.erlang-ls-0.0.19/client/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/Users/malte/.vscode/extensions/erlang-ls.erlang-ls-0.0.19/client/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/Users/malte/.vscode/extensions/erlang-ls.erlang-ls-0.0.19/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/malte/.vscode/extensions/erlang-ls.erlang-ls-0.0.19/client/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageWriter.fireClose (/Users/malte/.vscode/extensions/erlang-ls.erlang-ls-0.0.19/client/node_modules/vscode-jsonrpc/lib/messageWriter.js:39:27)
	at Socket.<anonymous> (/Users/malte/.vscode/extensions/erlang-ls.erlang-ls-0.0.19/client/node_modules/vscode-jsonrpc/lib/messageWriter.js:58:46)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:674:12)
```

**Comment by robertoaloi** [comment]
Hi @Daylien and thanks for reporting. I don't seem to be able to reproduce it locally, things seem to work normally for me.
I'm not a VS Code user myself, maybe @alanz has some ideas on how to troubleshoot this?
Also, we have a new version (`0.0.20`) of the extension available. Unlikely to solve the issue per se, but worth upgrading to it.

**Comment by Daylien** [comment]
Hey @robertoaloim, after the update to 0.0.20 the problem was resolved. If I downgrade to 0.0.19 the error is there. So yeah your latest push has resolved this issue.
